apiVersion: v1alpha1
kind: "Role"
metadata:
  name: hao-tag-graphql-use
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
  annotations:
    rbac.authorization.halo.run/dependencies: |
      [ "role-template-own-permissions", "role-template-public-apis" ]
rules:
  - nonResourceURLs: [ "/apis/api.plugin.halo.run/v1alpha1/plugins/HaoTag/github/*"]
    verbs: [ "get" ]